server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 5000ms
  servlet:
    context-path: /workspace

spring:
  application:
    name: workspace
  # ?? dev|test|prod
  profiles:
    active: dev
  # jackson?????
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #???????package?????????
  typeAliasesPackage: com.ogms.dge.workspace.modules.*.entity
  global-config:
    #???????
    db-config:
      #????  AUTO:"???ID??", INPUT:"????ID", ID_WORKER:"????ID (??????ID)", UUID:"????ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

container:
  api: "http://localhost:8080/container/"
  method:
    wd: "D:\\code\\dsc\\container\\method\\wd\\" # working directory方法工作路径
    pd: "D:\\code\\dsc\\container\\method\\pd\\" # package directory方法库存储路径
  data:
    fd: "D:\\code\\dsc\\container\\data\\file\\" # file directory文件存储路径
    td: "D:\\code\\dsc\\container\\data\\temp\\" # temp directory临时文件存储路径
    server: "http://112.4.132.6:8083/data" # 数据中转服务器地址
    dsd: "D:\\code\\dsc\\container\\data\\ds\\" # data source数据源实体存储路径

workspace:
  redis:
    open: true
  method:
    wd: "D:\\code\\dsc\\workspace\\method\\wd\\" # working directory方法工作路径
    insd: "D:\\code\\dsc\\workspace\\method\\ins\\" # package directory方法库存储路径
  data:
    fd: "D:\\code\\dsc\\workspace\\data\\file\\" # file directory文件存储路径
    td: "D:\\code\\dsc\\workspace\\data\\temp\\" # temp directory临时文件存储路径
    insd: "D:\\code\\dsc\\workspace\\data\\ins\\" # data instance实体存储路径
    server: "http://112.4.132.6:8083/data"
  workflow:
    fd: "D:\\code\\dsc\\workspace\\workflow\\file\\" # file directory工作流实体文件存储路径
  env:
    py: "C:\\Users\\lkshi\\.conda\\envs\\Python39\\"

# 项目目录
project:
  folder: D:/code/dsc/dge
